[package]
name = "wiimote-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["cesmec"]

[dependencies]
bitflags = "2.4"
crc32fast = "1.3"
crossbeam-channel = "0.5"

[build-dependencies]
cc = "1.0"
