name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - if: runner.os == 'Linux'
      name: Install dependencies
      run: sudo apt-get install -y libudev-dev libbluetooth-dev

    - name: Build
      run: cargo build --verbose

    - name: Build examples
      run: cargo build --verbose --examples

    - name: Run tests
      run: cargo test --verbose
