name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        required: false
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - if: runner.os == 'Linux'
      name: Install dependencies
      run: sudo apt-get install -y libudev-dev libbluetooth-dev clang

    - if: ${{ inputs.dry_run }}
      name: Publish dry-run
      run: cargo publish --dry-run

    - if: ${{ !inputs.dry_run }}
      name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish

    - if: ${{ !inputs.dry_run }}
      name: Set version variable
      run: echo "PACKAGE_VERSION=$(cargo pkgid | cut -d "#" -f2)" >> $GITHUB_ENV

    - if: ${{ !inputs.dry_run }}
      name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "v$PACKAGE_VERSION" --title "v$PACKAGE_VERSION"
